/**
 * scraper.js
 * Real-time Star Cineplex data via cineplex-ticket-api.cineplexbd.com
 *
 * Auth flow
 * ─────────
 * The guest-login endpoint requires a Google reCAPTCHA v3 token that
 * is generated by the SPA. We use Playwright to load the login page,
 * click "GUEST LOGIN", and intercept the resulting GET /guest-login
 * response to harvest the Bearer token. After that, every data call is
 * a plain fetch() — no browser needed.
 *
 * All endpoints use POST (even "gets").
 * Required headers on every call:
 *   Authorization: Bearer <token>
 *   appsource: web
 *   device-key: <static SHA-256 hash hardcoded in the SPA>
 *   Content-Type: application/json
 */

const { chromium } = require("playwright");
const path = require("path");
const fs = require("fs");

/* ─── Constants ──────────────────────────────────────────────── */

const BASE_URL = "https://cineplex-ticket-api.cineplexbd.com/api/v1";
const SITE_URL = "https://ticket.cineplexbd.com";
const DEVICE_KEY =
  "5e98df37da990542174d3849f031a58c0d89ae08a2156aed1133a236a0ccb778";

const DEBUG_DIR = path.join(__dirname, "data", "debug");

/* ─── Session state ──────────────────────────────────────────── */

const session = {
  token: null,
  locations: null, // cached: id → { id, code, locationTitle }
  browser: null,
};

/* ─── HTTP helper ────────────────────────────────────────────── */

async function apiPost(endpoint, body = {}) {
  if (!session.token)
    throw new Error("Not authenticated — call ensureSession() first");

  const res = await fetch(`${BASE_URL}${endpoint}`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${session.token}`,
      appsource: "web",
      "device-key": DEVICE_KEY,
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    throw new Error(`${endpoint} → HTTP ${res.status}`);
  }

  const json = await res.json();

  if (json.code === 401 || json.status === "unauthorized") {
    console.log("[scraper] Token expired — refreshing…");
    session.token = null;
    await ensureSession();
    return apiPost(endpoint, body);
  }

  return json.data ?? json;
}

/* ─── Guest login via Playwright ─────────────────────────────── */

async function ensureSession() {
  if (session.token) return;

  console.log("[scraper] Starting Playwright for guest login…");

  const browser = await chromium.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"],
  });
  const context = await browser.newContext({
    userAgent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
      "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
  });
  const page = await context.newPage();

  const tokenPromise = new Promise((resolve, reject) => {
    const timer = setTimeout(
      () => reject(new Error("Guest login timed out")),
      30000,
    );

    page.on("response", async (res) => {
      if (!res.url().includes("guest-login")) return;
      try {
        const json = await res.json();
        const token = json?.data?.token;
        if (token) {
          clearTimeout(timer);
          resolve(token);
        }
      } catch (_) {}
    });
  });

  try {
    await page.goto(`${SITE_URL}/login`, {
      waitUntil: "networkidle",
      timeout: 20000,
    });

    // Click "GUEST LOGIN" button (exact text as seen on the page)
    const guestBtn = page
      .locator("button", { hasText: /guest login/i })
      .first();
    await guestBtn.waitFor({ state: "visible", timeout: 10000 });
    await guestBtn.click();

    session.token = await tokenPromise;
    console.log("[scraper] Guest login successful — token acquired");

    // Save debug screenshot
    if (!fs.existsSync(DEBUG_DIR)) fs.mkdirSync(DEBUG_DIR, { recursive: true });
    await page
      .screenshot({ path: path.join(DEBUG_DIR, "guest-login.png") })
      .catch(() => {});
  } finally {
    await context.close();
    await browser.close();
  }
}

/* ─── Public API ─────────────────────────────────────────────── */

/**
 * Returns all cinema locations.
 * { id, code, locationTitle, totalScreen, district }
 */
async function getLocations() {
  await ensureSession();
  if (session.locations) return Object.values(session.locations);

  const data = await apiPost("/get-location");
  const list = Array.isArray(data) ? data : data.locations || [];

  session.locations = {};
  for (const loc of list) {
    session.locations[loc.id] = {
      id: loc.id,
      code: loc.code,
      locationTitle: loc.locationTitle,
      totalScreen: loc.totalScreen,
      district: loc.district,
    };
  }
  console.log(`[scraper] Loaded ${list.length} locations`);
  return list;
}

/**
 * Returns now-showing movies.
 * { id, slug, title, img, category, genre, release }
 */
async function getMovies() {
  await ensureSession();
  const data = await apiPost("/movie-list");

  // Response shape: { running: [], upcoming: [] }  OR  flat array
  const running = Array.isArray(data)
    ? data
    : data.running || data.movies || data.nowShowing || [];

  return running.map((m) => ({
    id: m.movie_id || m.id,
    slug: m.slug,
    title: m.title,
    poster: m.img || m.poster_url,
    category: m.category,
    genre: m.genre,
    release: m.release,
  }));
}

/**
 * Returns all unique dates on which movieId is showing across ALL locations.
 * Dates are ISO strings: "YYYY-MM-DD"
 */
async function getAvailableDates(movieId) {
  await ensureSession();
  const locations = await getLocations();

  // Parallel call for all locations
  const results = await Promise.allSettled(
    locations.map((loc) => apiPost("/get-showdate", { location: loc.id })),
  );

  const dateSet = new Set();
  for (const r of results) {
    if (r.status !== "fulfilled") continue;
    const rows = Array.isArray(r.value) ? r.value : [];
    for (const row of rows) {
      const movies = row.availableMovies || [];
      if (movies.some((m) => m.movie_id === movieId || m.id === movieId)) {
        dateSet.add(row.showDate);
      }
    }
  }

  return [...dateSet].sort();
}

/**
 * Full analysis for a movie + date across all locations.
 * Returns { movieId, movieTitle, showDate, shows[] }
 * Each show: { locationId, locationTitle, screenTitle, screenType,
 *              showTime, programId, categories[] }
 * Each category: { name, seatTypeId, totalSeats, availableSeats,
 *                  soldSeats, price }
 */
async function analyzeMovie(movieId, movieTitle, showDate) {
  await ensureSession();
  const locations = await getLocations();

  console.log(
    `[scraper] Analyzing "${movieTitle}" on ${showDate} across ${locations.length} locations…`,
  );

  // Step 1: get shows for all locations in parallel
  const showResults = await Promise.allSettled(
    locations.map((loc) =>
      apiPost("/get-shows", { location: loc.id, movieId, showDate }).then(
        (data) => ({ locId: loc.id, locTitle: loc.locationTitle, data }),
      ),
    ),
  );

  // Flatten into individual programId records
  const programIds = []; // { locId, locTitle, screenTitle, screenType, showTime, programId, seatPrices[] }

  for (const r of showResults) {
    if (r.status !== "fulfilled") continue;
    const { locId, locTitle, data } = r.value;
    const screens = Array.isArray(data) ? data : [];
    for (const screen of screens) {
      for (const showTime of screen.showTimes || []) {
        programIds.push({
          locId,
          locTitle,
          screenTitle: screen.screenTitle,
          screenType: screen.screenTypeName || screen.screenType,
          showTime: showTime.showTime,
          programId: showTime.programId,
          seatPrices: showTime.seatPrices || [],
        });
      }
    }
  }

  console.log(
    `[scraper] Found ${programIds.length} shows total — fetching seat data…`,
  );

  // Step 2: get seat data for each programId in parallel (batches of 10)
  const shows = [];
  const BATCH = 10;
  for (let i = 0; i < programIds.length; i += BATCH) {
    const batch = programIds.slice(i, i + BATCH);
    const seatResults = await Promise.allSettled(
      batch.map((p) =>
        apiPost("/get-seat", {
          programId: p.programId,
          location: p.locId,
        }).then((data) => ({ ...p, seatData: data })),
      ),
    );

    for (const r of seatResults) {
      if (r.status !== "fulfilled") {
        console.warn("[scraper] get-seat failed:", r.reason?.message);
        continue;
      }

      const p = r.value;

      // Build categories by joining get-shows seatPrices with get-seat seatTypes
      const categories = buildCategories(p.seatPrices, p.seatData);

      shows.push({
        locationId: p.locId,
        locationTitle: p.locTitle,
        screenTitle: p.screenTitle,
        screenType: p.screenType,
        showTime: formatTime(p.showTime),
        programId: p.programId,
        categories,
      });
    }
  }

  console.log(`[scraper] Done — ${shows.length} shows with seat data`);
  return { movieId, movieTitle, showDate, shows };
}

/* ─── Helpers ────────────────────────────────────────────────── */

/**
 * Join seat price info from get-shows with actual seat counts from get-seat.
 */
function buildCategories(seatPrices, seatData) {
  const categories = [];

  // Price lookup: seatTypeId → unitPrice (normalize casing)
  const priceMap = {};
  for (const sp of seatPrices || []) {
    const typeId = sp.seatTypeID ?? sp.seatTypeId ?? sp.seat_type_id;
    if (typeId != null) priceMap[String(typeId)] = sp.unitPrice;
  }

  const seatTypes = seatData?.seatTypes || [];

  for (const st of seatTypes) {
    const seats = st.seatStatus || [];
    const total = seats.length;
    const sold = seats.filter((s) => s.seatStatus === 0).length;
    const available = seats.filter((s) => s.seatStatus === 1).length;
    const price = priceMap[String(st.seatTypeId)] || 0;

    if (total === 0) continue; // skip empty/ghost seat types

    categories.push({
      name: st.seatTypeTitle,
      seatTypeId: st.seatTypeId,
      totalSeats: total,
      availableSeats: available,
      soldSeats: sold,
      price,
    });
  }

  return categories;
}

/** "14:15:00" → "2:15 PM" */
function formatTime(t) {
  if (!t) return "—";
  const [hStr, mStr] = t.split(":");
  let h = parseInt(hStr, 10);
  const m = mStr || "00";
  const ampm = h >= 12 ? "PM" : "AM";
  h = h % 12 || 12;
  return `${h}:${m} ${ampm}`;
}

/* ─── Reset session (for testing) ───────────────────────────── */
function resetSession() {
  session.token = null;
  session.locations = null;
}

module.exports = {
  getMovies,
  getLocations,
  getAvailableDates,
  analyzeMovie,
  ensureSession,
  resetSession,
};
